version: '3'

services:
  mongodb:
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - "8000:8000"